/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Computer.gltf --transform
Author: snrnsrk5 (https://sketchfab.com/snrnsrk5)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dell-ultrasharp-951c40459085466895fece243ceee8b2
Title: DELL UltraSharp
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Portfolio/Computer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.09, 0.15, 0]} scale={[0.08, 0.08, 0.16]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['.002']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Computer-transformed.glb')
