/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Skybox.gltf --transform
Author: An0n23 (https://sketchfab.com/an0n23)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-space-skybox-58f20e1770a14e6da386ba3b54834e52
Title: Earth Space Skybox
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Skybox-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, -10000, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Skybox_Material__37_0.geometry} material={materials.Material__37} />
            <mesh geometry={nodes.Skybox_Material__39_0.geometry} material={materials.Material__39} />
            <mesh geometry={nodes.Skybox_Material__36_0.geometry} material={materials.Material__36} />
            <mesh geometry={nodes.Skybox_Material__35_0.geometry} material={materials.Material__35} />
            <mesh geometry={nodes.Skybox_Material__34_0.geometry} material={materials.Material__34} />
            <mesh geometry={nodes.Skybox_Material__40_0.geometry} material={materials.Material__40} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skybox-transformed.glb')
